// =============================================================================
// Generated by egui RAD GUI Builder
// https://github.com/timschmidt/egui-rad-builder
// =============================================================================
// ^^This was a lifesaver, thank you so much lol


use eframe::egui::{self};
use enigo::{Button as EnigoButton, Direction, Enigo, Mouse, Settings};
use rdev::{EventType, Key};
use serde::{Deserialize, Serialize};
use spin_sleep;
use std::sync::{
    Arc,
    atomic::{AtomicBool, Ordering},
};
use std::thread;
use std::time::Duration;

use std::sync::mpsc::{self, Receiver};

struct GeneratedState {
    enable_top: bool,
    enable_bottom: bool,
    enable_left: bool,
    enable_right: bool,
    click_mode: usize,
    cps: f32,
    cdc: f32,
    save_name: String,
    input: String,
    output: String,
    is_running: bool,
    click_active: Option<Arc<AtomicBool>>,
    binding_input: bool,
    binding_output: bool,
    binding_input_rx: Option<Receiver<String>>,
    binding_output_rx: Option<Receiver<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
struct ProfileData {
    cps: f32,
    cdc: f32,
    input: String,
    output: String,
    click_mode: usize,
}

#[derive(Clone, Copy)]
struct ClickTiming {
    hold_us: u64,
    release_us: u64,
}

#[derive(Clone)]
struct ClickConfig {
    cps: f32,
    cdc: f32,
    input: String,
    output: String,
    click_mode: usize,
}

impl Default for GeneratedState {
    fn default() -> Self {
        Self {
            enable_top: false,
            enable_bottom: false,
            enable_left: false,
            enable_right: false,
            click_mode: 0,
            cps: 12.000,
            cdc: 42.000,
            save_name: "Profile1".to_owned(),
            input: "F6".to_owned(),
            output: "LEFT_MOUSE".to_owned(),
            is_running: false,
            click_active: None,
            binding_input: false,
            binding_output: false,
            binding_input_rx: None,
            binding_output_rx: None,
        }
    }
}

fn start_key_binding_listener(tx: std::sync::mpsc::Sender<String>) {
    thread::spawn(move || {
        let captured = Arc::new(AtomicBool::new(false));
        let captured_clone = Arc::clone(&captured);

        thread::sleep(Duration::from_millis(150));

        if let Err(err) = rdev::listen(move |event: rdev::Event| {
            if !captured_clone.load(Ordering::SeqCst) {
                match event.event_type {
                    EventType::KeyPress(key) => {
                        if let Some(key_name) = key_to_string(key) {
                            let _ = tx.send(key_name);
                            captured_clone.store(true, Ordering::SeqCst);
                        }
                    }
                    EventType::ButtonPress(button) => {
                        if let rdev::Button::Left = button {
                            return;
                        }

                        if let Some(button_name) = button_to_string(button) {
                            let _ = tx.send(button_name);
                            captured_clone.store(true, Ordering::SeqCst);
                        }
                    }
                    _ => {}
                }
            }
        }) {
            eprintln!("Failed to listen for binding events: {err:?}");
        }
    });
}

fn key_to_string(key: Key) -> Option<String> {
    match key {
        Key::F1 => Some("F1".to_string()),
        Key::F2 => Some("F2".to_string()),
        Key::F3 => Some("F3".to_string()),
        Key::F4 => Some("F4".to_string()),
        Key::F5 => Some("F5".to_string()),
        Key::F6 => Some("F6".to_string()),
        Key::F7 => Some("F7".to_string()),
        Key::F8 => Some("F8".to_string()),
        Key::F9 => Some("F9".to_string()),
        Key::F10 => Some("F10".to_string()),
        Key::F11 => Some("F11".to_string()),
        Key::F12 => Some("F12".to_string()),
        Key::Num0 => Some("0".to_string()),
        Key::Num1 => Some("1".to_string()),
        Key::Num2 => Some("2".to_string()),
        Key::Num3 => Some("3".to_string()),
        Key::Num4 => Some("4".to_string()),
        Key::Num5 => Some("5".to_string()),
        Key::Num6 => Some("6".to_string()),
        Key::Num7 => Some("7".to_string()),
        Key::Num8 => Some("8".to_string()),
        Key::Num9 => Some("9".to_string()),
        Key::KeyA => Some("A".to_string()),
        Key::KeyB => Some("B".to_string()),
        Key::KeyC => Some("C".to_string()),
        Key::KeyD => Some("D".to_string()),
        Key::KeyE => Some("E".to_string()),
        Key::KeyF => Some("F".to_string()),
        Key::KeyG => Some("G".to_string()),
        Key::KeyH => Some("H".to_string()),
        Key::KeyI => Some("I".to_string()),
        Key::KeyJ => Some("J".to_string()),
        Key::KeyK => Some("K".to_string()),
        Key::KeyL => Some("L".to_string()),
        Key::KeyM => Some("M".to_string()),
        Key::KeyN => Some("N".to_string()),
        Key::KeyO => Some("O".to_string()),
        Key::KeyP => Some("P".to_string()),
        Key::KeyQ => Some("Q".to_string()),
        Key::KeyR => Some("R".to_string()),
        Key::KeyS => Some("S".to_string()),
        Key::KeyT => Some("T".to_string()),
        Key::KeyU => Some("U".to_string()),
        Key::KeyV => Some("V".to_string()),
        Key::KeyW => Some("W".to_string()),
        Key::KeyX => Some("X".to_string()),
        Key::KeyY => Some("Y".to_string()),
        Key::KeyZ => Some("Z".to_string()),
        Key::Space => Some("SPACE".to_string()),
        Key::Tab => Some("TAB".to_string()),
        Key::Escape => Some("ESCAPE".to_string()),
        Key::Return => Some("RETURN".to_string()),
        Key::Backspace => Some("BACKSPACE".to_string()),
        Key::Delete => Some("DELETE".to_string()),
        Key::Insert => Some("INSERT".to_string()),
        Key::Home => Some("HOME".to_string()),
        Key::End => Some("END".to_string()),
        Key::PageUp => Some("PAGEUP".to_string()),
        Key::PageDown => Some("PAGEDOWN".to_string()),
        Key::UpArrow => Some("UP".to_string()),
        Key::DownArrow => Some("DOWN".to_string()),
        Key::LeftArrow => Some("LEFT".to_string()),
        Key::RightArrow => Some("RIGHT".to_string()),
        Key::ShiftLeft => Some("SHIFT".to_string()),
        Key::ShiftRight => Some("SHIFTRIGHT".to_string()),
        Key::ControlLeft => Some("CTRL".to_string()),
        Key::ControlRight => Some("CTRLRIGHT".to_string()),
        Key::Alt => Some("ALT".to_string()),
        Key::AltGr => Some("ALTGR".to_string()),
        Key::MetaLeft => Some("META".to_string()),
        Key::MetaRight => Some("METARIGHT".to_string()),
        _ => None,
    }
}

fn button_to_string(button: rdev::Button) -> Option<String> {
    match button {
        rdev::Button::Left => Some("LEFT_MOUSE".to_string()),
        rdev::Button::Right => Some("RIGHT_MOUSE".to_string()),
        rdev::Button::Middle => Some("MIDDLE_MOUSE".to_string()),
        rdev::Button::Unknown(8) => Some("Side1".to_string()),
        rdev::Button::Unknown(9) => Some("Side2".to_string()),
        _ => None,
    }
}

fn generated_ui(ctx: &egui::Context, state: &mut GeneratedState) {
    if let Some(rx) = &state.binding_input_rx {
        if let Ok(key_name) = rx.try_recv() {
            state.input = key_name;
            state.binding_input = false;
            state.binding_input_rx = None;
        }
    }

    if let Some(rx) = &state.binding_output_rx {
        if let Ok(button_name) = rx.try_recv() {
            state.output = button_name;
            state.binding_output = false;
            state.binding_output_rx = None;
        }
    }

    if state.enable_top {
        egui::TopBottomPanel::top("gen_top")
            .resizable(true)
            .show(ctx, |ui| {});
    }
    if state.enable_bottom {
        egui::TopBottomPanel::bottom("gen_bottom")
            .resizable(true)
            .show(ctx, |ui| {});
    }
    if state.enable_left {
        egui::SidePanel::left("gen_left")
            .resizable(true)
            .show(ctx, |ui| {});
    }
    if state.enable_right {
        egui::SidePanel::right("gen_right")
            .resizable(true)
            .show(ctx, |ui| {});
    }
    egui::CentralPanel::default().show(ctx, |ui| {
        let canvas = egui::Rect::from_min_size(ui.min_rect().min, egui::vec2(580.0, 500.0));
        let _ = ui.allocate_painter(canvas.size(), egui::Sense::hover());
        ui.push_id(("widget", 42), |ui| {
            ui.scope_builder(
                egui::UiBuilder::new().max_rect(egui::Rect::from_min_size(
                    canvas.min + egui::vec2(90.0, 196.0),
                    egui::vec2(180.0, 24.0),
                )),
                |ui| {
                    ui.horizontal(|ui| {
                        ui.label("CPS (Clicks Per Second)");
                        ui.add(
                            egui::DragValue::new(&mut state.cps)
                                .range(0.000..=1000.000)
                                .fixed_decimals(3),
                        );
                    });
                },
            );
        });
        ui.push_id(("widget", 43), |ui| {
            ui.scope_builder(
                egui::UiBuilder::new().max_rect(egui::Rect::from_min_size(
                    canvas.min + egui::vec2(90.0, 223.0),
                    egui::vec2(180.0, 24.0),
                )),
                |ui| {
                    ui.horizontal(|ui| {
                        ui.label("CDC (Click Duty Cycle)");
                        ui.add(
                            egui::DragValue::new(&mut state.cdc)
                                .range(0.000..=100.000)
                                .fixed_decimals(3),
                        );
                    });
                },
            );
        });
        ui.push_id(("widget", 46), |ui| {
            ui.scope_builder(
                egui::UiBuilder::new().max_rect(egui::Rect::from_min_size(
                    canvas.min + egui::vec2(0.0, 0.0),
                    egui::vec2(280.0, 250.0),
                )),
                |ui| {
                    egui::Frame::group(ui.style()).show(ui, |ui| {
                        ui.set_min_size(egui::vec2(268.0, 238.0));
                        ui.vertical(|ui| {
                            ui.strong("Clicker");
                            ui.separator();
                        });
                    });
                },
            );
        });
        ui.push_id(("widget", 47), |ui| {
            ui.scope_builder(
                egui::UiBuilder::new().max_rect(egui::Rect::from_min_size(
                    canvas.min + egui::vec2(0.0, 250.0),
                    egui::vec2(280.0, 250.0),
                )),
                |ui| {
                    egui::Frame::group(ui.style()).show(ui, |ui| {
                        ui.set_min_size(egui::vec2(268.0, 238.0));
                        ui.vertical(|ui| {
                            ui.strong("Input");
                            ui.separator();
                        });
                    });
                },
            );
        });
        ui.push_id(("widget", 49), |ui| {
            ui.scope_builder(
                egui::UiBuilder::new().max_rect(egui::Rect::from_min_size(
                    canvas.min + egui::vec2(15.0, 340.0),
                    egui::vec2(250.0, 112.0),
                )),
                |ui| {
                    let button_text = if state.binding_input {
                        "Click/Press any button"
                    } else {
                        &state.input
                    };
                    let input_button =
                        ui.add_sized(egui::vec2(250.0, 112.0), egui::Button::new(button_text));

                    if input_button.clicked() && !state.binding_input {
                        if state.is_running {
                            if let Some(active) = &state.click_active {
                                active.store(false, Ordering::SeqCst);
                            }
                            state.is_running = false;
                            state.click_active = None;
                        }
                        let (tx, rx) = mpsc::channel();
                        state.binding_input = true;
                        state.binding_input_rx = Some(rx);
                        start_key_binding_listener(tx);
                    }
                },
            );
        });
        ui.push_id(("widget", 50), |ui| {
            ui.scope_builder(
                egui::UiBuilder::new().max_rect(egui::Rect::from_min_size(
                    canvas.min + egui::vec2(280.0, 0.0),
                    egui::vec2(300.0, 350.0),
                )),
                |ui| {
                    egui::Frame::group(ui.style()).show(ui, |ui| {
                        ui.set_min_size(egui::vec2(288.0, 338.0));
                        ui.vertical(|ui| {
                            ui.strong("Profiles");
                            ui.separator();
                        });
                        egui::ScrollArea::vertical().show(ui, |ui| {
                            let profiles = load_profile_files();

                            if profiles.is_empty() {
                                ui.label("No profiles found");
                                return;
                            }

                            for profile in profiles {
                                let label =
                                    profile.strip_suffix(".json").unwrap_or(&profile).to_owned();

                                ui.horizontal(|ui| {
                                    if ui.add(egui::Button::new(label.clone())).clicked() {
                                        if let Err(err) = load_profile(state, &label) {
                                            eprintln!("{err}");
                                        }
                                    }

                                    ui.with_layout(
                                        egui::Layout::right_to_left(egui::Align::Center),
                                        |ui| {
                                            if ui.small_button("Delete").clicked() {
                                                if let Err(err) = delete_profile(&label) {
                                                    eprintln!("{err}");
                                                }
                                            }
                                        },
                                    );
                                });
                            }
                        });
                    });
                },
            );
        });
        ui.push_id(("widget", 51), |ui| {
            ui.scope_builder(
                egui::UiBuilder::new().max_rect(egui::Rect::from_min_size(
                    canvas.min + egui::vec2(290.0, 385.0),
                    egui::vec2(280.0, 38.0),
                )),
                |ui| {
                    ui.add_sized(
                        egui::vec2(280.0, 38.0),
                        egui::TextEdit::singleline(&mut state.save_name).hint_text("Type here"),
                    );
                },
            );
        });
        ui.push_id(("widget", 52), |ui| {
            ui.scope_builder(
                egui::UiBuilder::new().max_rect(egui::Rect::from_min_size(
                    canvas.min + egui::vec2(290.0, 435.0),
                    egui::vec2(130.0, 32.0),
                )),
                |ui| {
                    let save_button =
                        ui.add_sized(egui::vec2(130.0, 32.0), egui::Button::new("Save"));

                    if save_button.clicked() {
                        if let Err(err) = save_profile(state) {
                            eprintln!("{err}");
                        }
                    }
                },
            );
        });
        ui.push_id(("widget", 54), |ui| {
            ui.scope_builder(
                egui::UiBuilder::new().max_rect(egui::Rect::from_min_size(
                    canvas.min + egui::vec2(439.0, 435.0),
                    egui::vec2(130.0, 32.0),
                )),
                |ui| {
                    let button_text = if state.is_running { "Stop" } else { "Run" };
                    let run_button =
                        ui.add_sized(egui::vec2(130.0, 32.0), egui::Button::new(button_text));

                    if run_button.clicked() {
                        if state.is_running {
                            if let Some(active) = &state.click_active {
                                active.store(false, Ordering::SeqCst);
                            }
                            state.is_running = false;
                            state.click_active = None;
                        } else {
                            let config = ClickConfig {
                                cps: state.cps,
                                cdc: state.cdc,
                                input: state.input.clone(),
                                output: state.output.clone(),
                                click_mode: state.click_mode,
                            };

                            if let Some(active) = start_click_thread(config) {
                                state.is_running = true;
                                state.click_active = Some(active);
                            }
                        }
                    }
                },
            );
        });
        ui.push_id(("widget", 34), |ui| {
            ui.scope_builder(
                egui::UiBuilder::new().max_rect(egui::Rect::from_min_size(
                    canvas.min + egui::vec2(15.0, 196.0),
                    egui::vec2(70.0, 50.0),
                )),
                |ui| {
                    let items = vec!["Hold".to_string(), "Toggle".to_string()];
                    for (i, it) in items.iter().enumerate() {
                        if ui
                            .add(egui::RadioButton::new(state.click_mode == i, it))
                            .clicked()
                        {
                            state.click_mode = i;
                        }
                    }
                },
            );
        });
        ui.push_id(("widget", 35), |ui| {
            ui.scope_builder(
                egui::UiBuilder::new().max_rect(egui::Rect::from_min_size(
                    canvas.min + egui::vec2(15.0, 70.0),
                    egui::vec2(250.0, 112.0),
                )),
                |ui| {
                    let button_text = if state.binding_output {
                        "Click/Press any button"
                    } else {
                        &state.output
                    };
                    let output_button =
                        ui.add_sized(egui::vec2(250.0, 112.0), egui::Button::new(button_text));

                    if output_button.clicked() && !state.binding_output {
                        if state.is_running {
                            if let Some(active) = &state.click_active {
                                active.store(false, Ordering::SeqCst);
                            }
                            state.is_running = false;
                            state.click_active = None;
                        }
                        let (tx, rx) = mpsc::channel();
                        state.binding_output = true;
                        state.binding_output_rx = Some(rx);
                        start_key_binding_listener(tx);
                    }
                },
            );
        });
        ui.push_id(("widget", 53), |ui| {
            ui.scope_builder(
                egui::UiBuilder::new().max_rect(egui::Rect::from_min_size(
                    canvas.min + egui::vec2(280.0, 350.0),
                    egui::vec2(300.0, 150.0),
                )),
                |ui| {
                    egui::Frame::group(ui.style()).show(ui, |ui| {
                        ui.set_min_size(egui::vec2(288.0, 138.0));
                        ui.vertical(|ui| {
                            ui.strong("Save and Run");
                            ui.separator();
                        });
                    });
                },
            );
        });
    });
}


pub struct SharpClicks {
    state: GeneratedState,
}

impl Default for SharpClicks {
    fn default() -> Self {
        Self {
            state: Default::default(),
        }
    }
}

impl eframe::App for SharpClicks {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        generated_ui(ctx, &mut self.state);
    }
}

fn main() -> eframe::Result<()> {
    let native_options = eframe::NativeOptions {
        viewport: eframe::egui::ViewportBuilder::default()
            .with_title("SharpClicks")
            .with_resizable(false)
            .with_inner_size([600.0, 520.0]),
        ..Default::default()
    };
    eframe::run_native(
        "SharpClicks",
        native_options,
        Box::new(|_cc| Ok(Box::new(SharpClicks::default()))),
    )
}

fn load_profile_files() -> Vec<String> {
    let _ = std::fs::create_dir_all("profiles");

    let mut profiles = match std::fs::read_dir("profiles") {
        Ok(entries) => entries
            .filter_map(Result::ok)
            .filter_map(|entry| {
                let path = entry.path();
                if path.extension().and_then(|ext| ext.to_str()) == Some("json") {
                    Some(path.file_name()?.to_string_lossy().to_string())
                } else {
                    None
                }
            })
            .collect::<Vec<_>>(),
        Err(_) => Vec::new(),
    };

    profiles.sort();
    profiles
}

fn load_profile(state: &mut GeneratedState, profile_name: &str) -> Result<(), String> {
    let clean_name = profile_name.trim();
    if clean_name.is_empty() {
        return Err("Profile name cannot be empty".to_string());
    }

    let profile_dir = std::path::Path::new("profiles");
    let file_path = profile_dir.join(format!("{clean_name}.json"));
    let json = std::fs::read_to_string(&file_path)
        .map_err(|err| format!("Failed to read profile '{}': {err}", file_path.display()))?;

    let profile_data: ProfileData = serde_json::from_str(&json)
        .map_err(|err| format!("Failed to parse profile '{}': {err}", file_path.display()))?;

    state.cps = profile_data.cps;
    state.cdc = profile_data.cdc;
    state.input = profile_data.input;
    state.output = profile_data.output;
    state.click_mode = profile_data.click_mode;
    state.save_name = clean_name.to_string();

    Ok(())
}

fn save_profile(state: &GeneratedState) -> Result<(), String> {
    let profile_name = state.save_name.trim();

    if profile_name.is_empty() {
        return Err("Profile name cannot be empty".to_string());
    }

    let profile_dir = std::path::Path::new("profiles");
    std::fs::create_dir_all(profile_dir)
        .map_err(|err| format!("Failed to create profiles directory: {err}"))?;

    let profile_data = ProfileData {
        cps: state.cps,
        cdc: state.cdc,
        input: state.input.clone(),
        output: state.output.clone(),
        click_mode: state.click_mode,
    };

    let json = serde_json::to_string_pretty(&profile_data)
        .map_err(|err| format!("Failed to serialize profile: {err}"))?;

    let file_path = profile_dir.join(format!("{profile_name}.json"));
    std::fs::write(&file_path, json).map_err(|err| {
        format!(
            "Failed to write profile file '{}': {err}",
            file_path.display()
        )
    })?;

    Ok(())
}

fn delete_profile(profile_name: &str) -> Result<(), String> {
    let clean_name = profile_name.trim();
    if clean_name.is_empty() {
        return Err("Profile name cannot be empty".to_string());
    }

    let profile_dir = std::path::Path::new("profiles");
    let file_path = profile_dir.join(format!("{clean_name}.json"));

    if !file_path.exists() {
        return Err(format!("Profile '{}' does not exist", clean_name));
    }

    std::fs::remove_file(&file_path)
        .map_err(|err| format!("Failed to delete profile '{}': {err}", file_path.display()))?;

    Ok(())
}

fn click_timing_from_cps_cdc(cps: f32, cdc: f32, overhead_us: u64) -> ClickTiming {
    let cps = cps.max(0.001);
    let cdc = cdc.clamp(0.0, 100.0);

    let period_us = 1_000_000.0 / cps as f64;
    let hold_us = (period_us * (cdc as f64 / 100.0)).round() as u64;
    let release_us = period_us.round() as u64 - hold_us;

    let hold_us = hold_us.saturating_sub(overhead_us).max(500);
    let release_us = release_us.saturating_sub(overhead_us).max(500);

    let speed_compensation_modifier = if cps > 50.0 {
        1.015 
    } else {
        1.000
    };

    let hold_us = (hold_us as f64 / speed_compensation_modifier).round() as u64;
    let release_us = (release_us as f64 / speed_compensation_modifier).round() as u64;

    let hold_us = hold_us.saturating_sub(overhead_us).max(250); 
    let release_us = release_us.saturating_sub(overhead_us).max(250);

    ClickTiming {
        hold_us,
        release_us,
    }
}

fn parse_key(value: &str) -> Option<Key> {
    match value.trim().to_ascii_uppercase().as_str() {
        "F1" => Some(Key::F1),
        "F2" => Some(Key::F2),
        "F3" => Some(Key::F3),
        "F4" => Some(Key::F4),
        "F5" => Some(Key::F5),
        "F6" => Some(Key::F6),
        "F7" => Some(Key::F7),
        "F8" => Some(Key::F8),
        "F9" => Some(Key::F9),
        "F10" => Some(Key::F10),
        "F11" => Some(Key::F11),
        "F12" => Some(Key::F12),
        "0" | "NUM0" => Some(Key::Num0),
        "1" | "NUM1" => Some(Key::Num1),
        "2" | "NUM2" => Some(Key::Num2),
        "3" | "NUM3" => Some(Key::Num3),
        "4" | "NUM4" => Some(Key::Num4),
        "5" | "NUM5" => Some(Key::Num5),
        "6" | "NUM6" => Some(Key::Num6),
        "7" | "NUM7" => Some(Key::Num7),
        "8" | "NUM8" => Some(Key::Num8),
        "9" | "NUM9" => Some(Key::Num9),
        "KP0" | "KP_0" => Some(Key::Kp0),
        "KP1" | "KP_1" => Some(Key::Kp1),
        "KP2" | "KP_2" => Some(Key::Kp2),
        "KP3" | "KP_3" => Some(Key::Kp3),
        "KP4" | "KP_4" => Some(Key::Kp4),
        "KP5" | "KP_5" => Some(Key::Kp5),
        "KP6" | "KP_6" => Some(Key::Kp6),
        "KP7" | "KP_7" => Some(Key::Kp7),
        "KP8" | "KP_8" => Some(Key::Kp8),
        "KP9" | "KP_9" => Some(Key::Kp9),
        "A" | "KEYA" => Some(Key::KeyA),
        "B" | "KEYB" => Some(Key::KeyB),
        "C" | "KEYC" => Some(Key::KeyC),
        "D" | "KEYD" => Some(Key::KeyD),
        "E" | "KEYE" => Some(Key::KeyE),
        "F" | "KEYF" => Some(Key::KeyF),
        "G" | "KEYG" => Some(Key::KeyG),
        "H" | "KEYH" => Some(Key::KeyH),
        "I" | "KEYI" => Some(Key::KeyI),
        "J" | "KEYJ" => Some(Key::KeyJ),
        "K" | "KEYK" => Some(Key::KeyK),
        "L" | "KEYL" => Some(Key::KeyL),
        "M" | "KEYM" => Some(Key::KeyM),
        "N" | "KEYN" => Some(Key::KeyN),
        "O" | "KEYO" => Some(Key::KeyO),
        "P" | "KEYP" => Some(Key::KeyP),
        "Q" | "KEYQ" => Some(Key::KeyQ),
        "R" | "KEYR" => Some(Key::KeyR),
        "S" | "KEYS" => Some(Key::KeyS),
        "T" | "KEYT" => Some(Key::KeyT),
        "U" | "KEYU" => Some(Key::KeyU),
        "V" | "KEYV" => Some(Key::KeyV),
        "W" | "KEYW" => Some(Key::KeyW),
        "X" | "KEYX" => Some(Key::KeyX),
        "Y" | "KEYY" => Some(Key::KeyY),
        "Z" | "KEYZ" => Some(Key::KeyZ),
        "SPACE" => Some(Key::Space),
        "TAB" => Some(Key::Tab),
        "ESC" | "ESCAPE" => Some(Key::Escape),
        "ENTER" | "RETURN" | "KPRETURN" => Some(Key::Return),
        "BACKSPACE" => Some(Key::Backspace),
        "DELETE" => Some(Key::Delete),
        "INSERT" => Some(Key::Insert),
        "HOME" => Some(Key::Home),
        "END" => Some(Key::End),
        "PAGEUP" | "PAGEDOWN_PREV" => Some(Key::PageUp),
        "PAGEDOWN" | "PAGEDOWN_NEXT" => Some(Key::PageDown),
        "UP" | "UPARROW" => Some(Key::UpArrow),
        "DOWN" | "DOWNARROW" => Some(Key::DownArrow),
        "LEFT" | "LEFTARROW" => Some(Key::LeftArrow),
        "RIGHT" | "RIGHTARROW" => Some(Key::RightArrow),
        "SHIFT" | "SHIFTLEFT" => Some(Key::ShiftLeft),
        "SHIFTRIGHT" => Some(Key::ShiftRight),
        "CTRL" | "CONTROL" | "CONTROLLEFT" => Some(Key::ControlLeft),
        "CTRLRIGHT" | "CONTROLRIGHT" => Some(Key::ControlRight),
        "ALT" => Some(Key::Alt),
        "ALTGR" => Some(Key::AltGr),
        "META" | "METALEFT" => Some(Key::MetaLeft),
        "METARIGHT" | "META_RIGHT" => Some(Key::MetaRight),
        "CAPSLOCK" | "CAPS" => Some(Key::CapsLock),
        "NUMLOCK" | "NUM_LOCK" => Some(Key::NumLock),
        "SCROLLLOCK" | "SCROLL_LOCK" => Some(Key::ScrollLock),
        "KP_PLUS" | "KPPLUS" => Some(Key::KpPlus),
        "KP_MINUS" | "KPMINUS" => Some(Key::KpMinus),
        "KP_MULTIPLY" | "KPMULTIPLY" => Some(Key::KpMultiply),
        "KP_DIVIDE" | "KPDIVIDE" => Some(Key::KpDivide),
        "KP_DELETE" | "KPDELETE" => Some(Key::KpDelete),
        "PRINTSCREEN" | "PRINT" => Some(Key::PrintScreen),
        "PAUSE" => Some(Key::Pause),
        "BACKQUOTE" | "BACKTICK" | "`" => Some(Key::BackQuote),
        "MINUS" | "-" => Some(Key::Minus),
        "EQUAL" | "=" => Some(Key::Equal),
        "LEFTBRACKET" | "[" => Some(Key::LeftBracket),
        "RIGHTBRACKET" | "]" => Some(Key::RightBracket),
        "SEMICOLON" | ";" => Some(Key::SemiColon),
        "QUOTE" | "\"" | "'" => Some(Key::Quote),
        "BACKSLASH" | "\\" => Some(Key::BackSlash),
        "INTLBACKSLASH" => Some(Key::IntlBackslash),
        "COMMA" | "," => Some(Key::Comma),
        "DOT" | "PERIOD" | "." => Some(Key::Dot),
        "SLASH" | "/" => Some(Key::Slash),
        _ => None,
    }
}

fn parse_button(value: &str) -> Option<EnigoButton> {
    match value.trim().to_ascii_uppercase().as_str() {
        "LEFT_MOUSE" | "LEFT" | "BUTTON1" => Some(EnigoButton::Left),
        "RIGHT_MOUSE" | "RIGHT" | "BUTTON2" => Some(EnigoButton::Right),
        "MIDDLE_MOUSE" | "MIDDLE" | "BUTTON3" => Some(EnigoButton::Middle),
        "SIDE1" | "BACK" | "BACK_BUTTON" | "BUTTON4" => Some(EnigoButton::Back),
        "SIDE2" | "FORWARD" | "FORWARD_BUTTON" | "BUTTON5" => Some(EnigoButton::Forward),
        "SCROLL_UP" | "SCROLLUP" | "WHEEL_UP" => Some(EnigoButton::ScrollUp),
        "SCROLL_DOWN" | "SCROLLDOWN" | "WHEEL_DOWN" => Some(EnigoButton::ScrollDown),
        "SCROLL_LEFT" | "SCROLLLEFT" | "WHEEL_LEFT" => Some(EnigoButton::ScrollLeft),
        "SCROLL_RIGHT" | "SCROLLRIGHT" | "WHEEL_RIGHT" => Some(EnigoButton::ScrollRight),
        _ => None,
    }
}

fn start_click_thread(config: ClickConfig) -> Option<Arc<AtomicBool>> {
    let trigger = parse_key(&config.input);

    let input_lower = config.input.to_lowercase();
    if trigger.is_none() && input_lower != "side1" && input_lower != "side2" {
        eprintln!(
            "Warning: Unsupported keyboard input key '{}'; defaulting listener fallback to F6",
            config.input
        );
    }

    let output_button = match parse_button(&config.output) {
        Some(button) => button,
        None => {
            eprintln!(
                "Unsupported output button '{}'; defaulting to Left",
                config.output
            );
            EnigoButton::Left
        }
    };
    let global_running = Arc::new(AtomicBool::new(true));

    let click_enabled = Arc::new(AtomicBool::new(false));

    let click_enabled_loop = Arc::clone(&click_enabled);
    let click_enabled_listener = Arc::clone(&click_enabled);
    let global_running_loop = Arc::clone(&global_running);
    let global_running_listener = Arc::clone(&global_running);

    thread::spawn(move || {
        let mut enigo = Enigo::new(&Settings::default()).expect("failed to create Enigo instance");

        enigo.set_delay(0);

        let calibration_iterations = 20;
        let start_time = std::time::Instant::now();

        for _ in 0..calibration_iterations {
            let _ = enigo.button(output_button, Direction::Release);
        }

        let total_elapsed = start_time.elapsed().as_micros() as u64;
        let detected_overhead_us = total_elapsed / calibration_iterations;

        let device_overhead_us = detected_overhead_us.clamp(50, 500);
        println!(
            "SharpClicks: Calibrated device input overhead to {}µs",
            device_overhead_us
        );

        let spin_sleeper = spin_sleep::SpinSleeper::new(200_000)
            .with_spin_strategy(spin_sleep::SpinStrategy::SpinLoopHint);

        while global_running_loop.load(Ordering::SeqCst) {
            if click_enabled_loop.load(Ordering::SeqCst) {
                let timing = click_timing_from_cps_cdc(config.cps, config.cdc, device_overhead_us);

                enigo.button(output_button, Direction::Press).ok();
                spin_sleeper.sleep(Duration::from_micros(timing.hold_us));

                enigo.button(output_button, Direction::Release).ok();
                spin_sleeper.sleep(Duration::from_micros(timing.release_us));
            } else {
                spin_sleeper.sleep(Duration::from_millis(10));
            }
        }
    });

    thread::spawn(move || {
        use std::io::Write;

        println!("SharpClicks: Initializing global OS event hook...");
        let _ = std::io::stdout().flush();

        if let Err(err) = rdev::listen(move |event: rdev::Event| {
            if !global_running_listener.load(Ordering::SeqCst) {
                return;
            }

            if let EventType::MouseMove { .. } = event.event_type {
                return;
            }

            let is_trigger_active = match &event.event_type {
                EventType::KeyPress(key) => parse_key(&config.input).map_or(false, |k| k == *key),
                EventType::ButtonPress(button) => {
                    println!("SharpClicks Debug -> Pressed: {:?}", button);
                    let _ = std::io::stdout().flush();

                    match button {
                        rdev::Button::Unknown(8) => config.input.to_lowercase() == "side1",
                        rdev::Button::Unknown(9) => config.input.to_lowercase() == "side2",
                        rdev::Button::Left => config.input.to_ascii_uppercase() == "LEFT_MOUSE",
                        rdev::Button::Right => config.input.to_ascii_uppercase() == "RIGHT_MOUSE",
                        rdev::Button::Middle => config.input.to_ascii_uppercase() == "MIDDLE_MOUSE",
                        _ => false,
                    }
                }
                _ => false,
            };

            let is_trigger_released = match &event.event_type {
                EventType::KeyRelease(key) => parse_key(&config.input).map_or(false, |k| k == *key),
                EventType::ButtonRelease(button) => match button {
                    rdev::Button::Unknown(8) => config.input.to_lowercase() == "side1",
                    rdev::Button::Unknown(9) => config.input.to_lowercase() == "side2",
                    rdev::Button::Left => config.input.to_ascii_uppercase() == "LEFT_MOUSE",
                    rdev::Button::Right => config.input.to_ascii_uppercase() == "RIGHT_MOUSE",
                    rdev::Button::Middle => config.input.to_ascii_uppercase() == "MIDDLE_MOUSE",
                    _ => false,
                },
                _ => false,
            };

            if is_trigger_active {
                if config.click_mode == 1 {
                    let next = !click_enabled_listener.load(Ordering::SeqCst);
                    click_enabled_listener.store(next, Ordering::SeqCst);
                } else {
                    click_enabled_listener.store(true, Ordering::SeqCst);
                }
            } else if is_trigger_released {
                if config.click_mode == 0 {
                    click_enabled_listener.store(false, Ordering::SeqCst);
                }
            }
        }) {
            eprintln!("CRITICAL ERROR: Failed to attach global system hook: {err:?}");
        }
    });

    Some(global_running)
}
